---
title: "Quantmod IV"
author: "cms"
date: "9/4/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(PerformanceAnalytics)
library(quantmod)
library(tidyverse)
options("getSymbols.yahoo.warning"=FALSE)
options("getSymbols.warning4.0"=FALSE)
```


```{r}

getSymbols("MSFT")
price <- Cl(MSFT) # close price
r <- price/Lag(price) - 1 # % price change
delta <-0.005 #threshold
signal <-c(0) # first date has no signal

#Loop over all trading days (except the first)
for (i in 2: length(price)){
  if (r[i] > delta){
    signal[i]<- 1
  } else
    signal[i]<- 0
}
signal<-reclass(signal,price)
tail(signal, n=20)

```

# Calculate Return when Filter says "BUY"

```{r}
trade <- Lag(signal,1)
ret <- dailyReturn(MSFT)*trade
names(ret) <- "filter"
charts.PerformanceSummary(ret, main = "Simple Filter")
```


#  Start Building Out New Model
```{r}
day <- 14
price <- Cl(MSFT)
signal <- c(0)
rsi <- RSI(price, day)


```


# Complete For Loop
```{r}
signal[1:day + 1] <- 0

for(i in (day + 1):length(price)){
  if(rsi[i] < 50){
    signal[i] <- 1
  } else{
    signal[i] <- 0
  }
}
head(signal, 10)
signal <- reclass(signal, Cl(MSFT))
head(signal, 10)
```

#Calculate Return on Traded Days


```{r}
trade2 <- Lag(signal)
ret2 <- dailyReturn(MSFT)*trade2
head(ret2,20)

```

#Combine Simple and RSI Filters into One and Plot

```{r}
names(ret) <- "Simple"
names(ret2) <- "RSI"
retcomb <- cbind(ret, ret2)
head(retcomb,6)
charts.PerformanceSummary(retcomb, main = "Simple Filter vs RSI Filter")
```






































```{r}

```

